# Generated by Django 4.2.4 on 2023-08-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='auther',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default='', null=True),
        ),
    ]
